language: php

php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - chmod +x vendor/bin/phpunit
   - chmod +x vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)